<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331124825 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE driver (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) DEFAULT NULL, worked_time INT DEFAULT NULL, is_active BOOLEAN NOT NULL, company_depot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_11667CD99D87C1B3 ON driver (company_depot_id)');
        $this->addSql('ALTER TABLE driver ADD CONSTRAINT FK_11667CD99D87C1B3 FOREIGN KEY (company_depot_id) REFERENCES company_depot (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE driver DROP CONSTRAINT FK_11667CD99D87C1B3');
        $this->addSql('DROP TABLE driver');
    }
}
