<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260330132223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE global_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, average_speed INT DEFAULT NULL, loading_time INT DEFAULT NULL, unloading_time INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3223F6EB979B1AD6 ON global_settings (company_id)');
        $this->addSql('ALTER TABLE global_settings ADD CONSTRAINT FK_3223F6EB979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE global_settings DROP CONSTRAINT FK_3223F6EB979B1AD6');
        $this->addSql('DROP TABLE global_settings');
    }
}
